flowchart LR

subgraph 0["src"]
1["App.jsx"]
subgraph 2["components"]
subgraph 3["Applications"]
4["Applications.jsx"]
F["ApplicationEditorPanel.jsx"]
O["ApplicationEditorModules.jsx"]
P["ApplicationEditorSettings.jsx"]
end
subgraph D["shared"]
E["ConfirmWithInputDialog.jsx"]
12["JsonSchemaBuilder.jsx"]
15["CopyButton.jsx"]
16["ObjectTypeSelect.jsx"]
17["MultipleSelect.jsx"]
19["ScheduleConfig.jsx"]
1M["DownloadJsonButton.jsx"]
2F["ObjectTypeNav.jsx"]
2O["PanelBreadcrumb.jsx"]
2T["DataPanel.jsx"]
2V["EntryToolbar.jsx"]
end
subgraph K["Firewall"]
subgraph L["Routes"]
M["routesPolicyUtils.js"]
1E["RoutesPanel.jsx"]
1F["GlobalRoutesPolicy.jsx"]
1G["DisabledRouteResponse.jsx"]
1H["RoutesPolicyTree.jsx"]
1I["RouteSettingsDrawer.jsx"]
1J["RoutesPolicyNodeContent.jsx"]
1K["routesPolicyReducer.js"]
1L["TestPolicyPanel.jsx"]
3E["RoutesPolicyUsersPopover.jsx"]
end
subgraph Q["Users"]
R["AuthManager.jsx"]
S["HttpMethodsSelector.jsx"]
T["RateLimit.jsx"]
1N["RestApiSingleUser.jsx"]
1O["Users.jsx"]
1P["UserEditor.jsx"]
end
end
N["LoadingMessage.jsx"]
subgraph U["IpFilter"]
V["AllowedIps.jsx"]
X["AllowedOrigins.jsx"]
1T["IpFilter.jsx"]
1U["CountryBlockList.jsx"]
1V["IpDataGrid.jsx"]
1W["ReleaseTime.jsx"]
1X["PublicRateLimitSection.jsx"]
end
subgraph Z["Automations"]
10["Automations.jsx"]
11["AutomationEditor.jsx"]
1A["HookRegistry.jsx"]
3D["HookDiscovery.jsx"]
end
subgraph 13["Models"]
14["Properties.jsx"]
18["GlobalProperties.jsx"]
2E["Collections.jsx"]
2G["CollectionEditor.jsx"]
2P["SortCollectionsUtils.jsx"]
2Q["ModelsPanel.jsx"]
2R["Models.jsx"]
2S["ModelEditor.jsx"]
2U["PropertiesPanel.jsx"]
end
subgraph 1B["Configuration"]
1C["ConfigurationDialog.jsx"]
end
1D["ConfirmDialog.jsx"]
subgraph 1Q["GlobalSecurity"]
1R["GlobalSecurity.jsx"]
end
subgraph 1Y["License"]
1Z["License.jsx"]
20["ProFeatures.jsx"]
end
subgraph 21["LoginHardening"]
22["LoginHardening.jsx"]
end
subgraph 23["Logs"]
24["Logs.jsx"]
25["LogsGraphView.jsx"]
end
subgraph 26["Mails"]
27["MailsPanel.jsx"]
28["Mails.jsx"]
29["MailEditor.jsx"]
2A["Smtp.jsx"]
end
subgraph 2C["Migration"]
2D["MigrationDialog.jsx"]
3F["ProToFreeDialog.jsx"]
end
2H["Navigation.jsx"]
2I["AppIdentity.jsx"]
2J["ApplicationSelector.jsx"]
subgraph 2K["Documentation"]
2L["Documentation.jsx"]
end
subgraph 2W["Theme"]
2X["ThemeSettings.jsx"]
2Y["DeployTheme.jsx"]
end
subgraph 2Z["Webhooks"]
30["Webhook.jsx"]
31["WebhookAuth.jsx"]
32["WebhookAuthCustom.jsx"]
33["WebhookAuthGenerated.jsx"]
34["WebhookTest.jsx"]
35["WordpressEvents.jsx"]
36["Webhooks.jsx"]
37["WebhookEditor.jsx"]
38["WebhookEditorSecretManager.jsx"]
end
subgraph 39["WordPressMode"]
3A["WordPressMode.jsx"]
end
end
subgraph 5["contexts"]
6["AdminDataContext.jsx"]
7["ApplicationContext.jsx"]
8["LicenseContext.jsx"]
9["NavigationContext.jsx"]
A["DialogContext.jsx"]
H["EntryToolbarContext.jsx"]
2M["DocumentationContext.jsx"]
end
subgraph B["hooks"]
C["useProActions.js"]
G["useRegisterToolbar.js"]
1S["useSaveOptions.js"]
2B["useSettingsForm.js"]
3G["useAjax.js"]
end
subgraph I["utils"]
J["formatDate.js"]
W["sanitizeIp.js"]
Y["sanitizeHost.js"]
2N["contentStyles.js"]
3I["sanitizeHtml.js"]
3J["sprintf.js"]
end
3B["AppTheme.jsx"]
3C["Footer.jsx"]
3H["index.js"]
end
1-->4
1-->10
1-->1C
1-->1D
1-->1E
1-->1N
1-->1O
1-->1R
1-->1T
1-->1Z
1-->22
1-->24
1-->27
1-->2D
1-->2E
1-->2Q
1-->2U
1-->2H
1-->2V
1-->2X
1-->30
1-->36
1-->3A
1-->6
1-->7
1-->A
1-->H
1-->8
1-->9
1-->1S
1-->2B
4-->6
4-->7
4-->8
4-->9
4-->C
4-->E
4-->F
7-->6
7-->8
9-->7
9-->A
C-->6
C-->A
C-->8
F-->6
F-->7
F-->8
F-->9
F-->C
F-->G
F-->J
F-->M
F-->N
F-->E
F-->O
F-->P
G-->7
G-->H
P-->R
P-->S
P-->T
P-->V
P-->X
R-->6
V-->W
X-->6
X-->7
X-->A
X-->8
X-->Y
10-->6
10-->7
10-->8
10-->9
10-->C
10-->J
10-->11
10-->1A
11-->6
11-->7
11-->8
11-->C
11-->G
11-->J
11-->N
11-->12
11-->19
12-->14
14-->6
14-->8
14-->15
14-->16
14-->18
16-->6
16-->17
18-->8
1A-->6
1A-->8
1C-->6
1C-->A
1C-->8
1D-->A
1E-->6
1E-->7
1E-->8
1E-->9
1E-->C
1E-->1F
1E-->1H
1F-->8
1F-->16
1F-->1G
1G-->6
1G-->7
1G-->8
1H-->6
1H-->8
1H-->1I
1H-->1J
1H-->1K
1H-->M
1H-->1L
1I-->V
1I-->X
1I-->M
1J-->6
1J-->8
1J-->15
1J-->M
1K-->M
1L-->6
1L-->7
1L-->8
1L-->15
1L-->1M
1N-->6
1N-->8
1N-->V
1N-->R
1N-->T
1O-->6
1O-->7
1O-->8
1O-->9
1O-->C
1O-->1P
1P-->6
1P-->7
1P-->8
1P-->9
1P-->C
1P-->G
1P-->J
1P-->N
1P-->R
1P-->S
1P-->T
1R-->6
1R-->7
1R-->A
1R-->1S
1R-->15
1S-->6
1S-->A
1S-->8
1T-->7
1T-->8
1T-->9
1T-->1U
1T-->1V
1T-->1X
1U-->6
1U-->8
1U-->C
1U-->N
1V-->6
1V-->8
1V-->W
1V-->1W
1W-->6
1W-->8
1X-->6
1X-->1S
1X-->T
1Z-->6
1Z-->8
1Z-->20
22-->6
22-->7
22-->1S
24-->6
24-->7
24-->8
24-->C
24-->J
24-->25
27-->7
27-->8
27-->9
27-->28
27-->2A
28-->6
28-->8
28-->C
28-->J
28-->29
29-->6
29-->7
29-->8
29-->C
29-->G
29-->J
2A-->6
2A-->8
2A-->1S
2A-->2B
2D-->6
2D-->8
2E-->6
2E-->7
2E-->A
2E-->8
2E-->9
2E-->C
2E-->1S
2E-->2F
2E-->2G
2E-->2P
2G-->6
2G-->7
2G-->A
2G-->8
2G-->C
2G-->G
2G-->1S
2G-->2H
2G-->2P
2H-->6
2H-->7
2H-->H
2H-->8
2H-->9
2H-->C
2H-->2I
2H-->2J
2H-->2L
2H-->2O
2I-->6
2J-->7
2J-->8
2J-->9
2L-->2M
2L-->2N
2M-->6
2O-->7
2O-->9
2Q-->6
2Q-->7
2Q-->8
2Q-->9
2Q-->1S
2Q-->2B
2Q-->18
2Q-->2R
2R-->6
2R-->7
2R-->8
2R-->C
2R-->16
2R-->2S
2S-->6
2S-->7
2S-->A
2S-->8
2S-->9
2S-->C
2S-->G
2S-->J
2S-->N
2S-->2T
2S-->12
2S-->14
2T-->15
2U-->6
2U-->8
2U-->9
2U-->2F
2U-->18
2U-->14
2V-->A
2V-->2L
2V-->2H
2V-->2O
2X-->2Y
2Y-->6
30-->31
30-->34
30-->35
31-->6
31-->8
31-->32
31-->33
34-->6
34-->15
35-->6
35-->8
35-->17
36-->6
36-->7
36-->8
36-->9
36-->C
36-->37
37-->6
37-->7
37-->8
37-->C
37-->G
37-->J
37-->N
37-->19
37-->38
38-->32
38-->33
3A-->6
3A-->7
3A-->A
3A-->8
3A-->1S
3A-->V
3A-->15
3C-->6
3D-->6
3D-->8
3F-->6
3G-->6
3G-->8
3H-->1
3H-->3B
3H-->6
3H-->2M
3H-->8
3H-->3C
